apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food-app-ingress
spec:
  ingressClassName: nginx

  rules:
  - host: zeeshan.agency
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: food-app-service
            port:
              number: 80
